noun = raw_input("Enter a noun: ")
verb = raw_input("Enter a verb in base form: ")
relation = raw_input("Enter a relation: ")
greeting = raw_input("Enter a greeting: ")
verb_2 = raw_input("Enter a verb in base form: ")
feeling = raw_input("Enter a feeling: ")
time_frame = raw_input("Enter a time frame: ")
verb_3 = raw_input("Enter a verb in base form: ")
event = raw_input("Enter an event: ")
verb_4 = raw_input("Enter an -ing verb: ")
body_part = raw_input("Enter a body part: ")
first_name = raw_input("Enter a name: ")
adjective = raw_input("Enter an adjective: ")
relation = raw_input("Enter a relation: ")
noun_2 = raw_input("Enter a noun: ")

print "Do you want to annoy the people around you for %s, or just for fun? Are you already an annoying person who wants to %s your skills? Are you trying to annoy someone specific, such as your teacher or your %s? Whatever your reason, unless you want to be annoying, read on! 1. Say %s to someone, and when they say hello back, scream at them, ~What the heck is your problem, man?~ 2. Reply to everything someone says with ~that's what YOU %s ( Ex : Our little bundle of %s should be due sometime next %s You: ~That's what you %s ~ 3. Randomly ask anybody you see, ~When is your %s? ~ 4. When in an elevator, randomly start %s any song that comes to %s. 5. Call someone by the wrong name, and make them think that they're somehow related to you. ( Ex : ~ %s, my %s %s! How's the %s going? ~ " % ()
